NumPy - Numerical Python

helpful for list and tuples.
nupy array is same as above but more advantageous we can do more operation

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [2]:
import numpy as np

In [1]:
import  numpy as np

In [3]:
#libreries are pre made coded module whre 1000 of codes are alredy built in 
# insted of recoding it , we call it for more coding operations


List vs Numpy - Time Taken

In [4]:
from time import process_time


In [5]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0017722080000002194


In [26]:
python_list = [i for i in range(10000)]
start_time= process_time()
python_list= [i+5 for i in python_list]
end_time= process_time()
print(end_time-start_time)


0.0006859009999988785


In [11]:
# python_list we can call the list by that name

In [20]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0008640510000006429


In [25]:
np_array = np.array ([i for i in range(10000)])
start_time- process_time()
np_array += 5
end_time=process_time()
print(end_time - start_time)



0.6063289540000003


In [27]:
np_array = np.array ([i for i in range(10000)])
start_time- process_time()
np_array += 5
end_time=process_time()
print(end_time - start_time)


0.05307075500000025


# Conclusion numpy array will make more faster operation than list in python



Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [29]:
# list
list1= [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array) # arrays are similar to matrixes

[1 2 3 4 5]


numpy.ndarray

In [31]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [34]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
# creating one dimensional array
a = np.array([1,2,3,4,5,])
print(a)
type(a) # one row


[1 2 3 4 5]


numpy.ndarray

In [33]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
b = np.array([(1,2,3,4),(5,6,7,8)]) # 2 rows 4 column
print(b)
type(b)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

In [39]:
b.shape # 1st represent row num , 2nd represent column no.

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [48]:
c = np.array([[(1,2,3),(4,5,6)]],dtype=float)
print(c)

[[[1. 2. 3.]
  [4. 5. 6.]]]


Initial Placeholders in numpy arrays - untial value present in numpy array

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
# create a numpy arrays with 0 , we need to use double paranthesis

x = np.zeros((2,3)) # by default it taking float
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
x=np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [50]:
# array with perticualr value


x= np.full((4,4),9)
x

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
# create an identity matrix , a;; the diagonal value is one and all other vale is 0
# it alwasy have same rows and column is equal
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
a= np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.06180442 0.35700298 0.90695408 0.03091635]
 [0.58655837 0.66048197 0.29741526 0.89522409]
 [0.75529751 0.8197227  0.89382064 0.85936446]]


In [57]:
x = np.random.random((3,3)) # all the vale b/w 0 and 1
x

array([[0.28773433, 0.56806787, 0.45395018],
       [0.94221043, 0.66408323, 0.28218118],
       [0.60638017, 0.31132584, 0.49038795]])

In [60]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5)) # random integer witin a specific range
print(c)

[[24 29 77 22 18]
 [12 82 10 64 88]
 [12 43 30 45 97]]


In [68]:
c = np.random.randint(10,100,(3,5))
c

array([[96, 82, 42, 23, 95],
       [26, 36, 66, 53, 87],
       [79, 35, 95, 88, 41]])

In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [73]:
d= np.linspace(2,20,5) # no. value we want with evenly spaced 
d

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [ ]:
# array of evenly spaced values --> specifying the step means adding the +5 
# to the next number
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [77]:
d= np.arange(2,20,5) 
d

array([ 2,  7, 12, 17])

In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [81]:
list = [1,2,3,4,5]
np_array= np.asarray(list)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[66 80 57 82 62]
 [61 81 62 75 65]
 [24 43 42 35 11]
 [64 70 50 80 45]
 [70 23 53 80 23]]


In [83]:
x = np.random.randint(10,100,(4,4))
x

array([[52, 43, 38, 83],
       [30, 33, 51, 65],
       [74, 45, 95, 10],
       [39, 16, 93, 63]])

In [84]:
# array dimension
print(c.shape)
x.shape

(3, 5)


(4, 4)

In [85]:
# number of dimensions
print(c.ndim)
x.ndim

2


2

In [86]:
# number of elements in an array
print(c.size)
x.size

15


16

In [89]:
# checking the data type of the values in the array
print(c.dtype)
x.dtype

int64


dtype('int64')

Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 2 0]
 [8 8 6]
 [5 7 0]]
[[15 10 13]
 [18 14 14]
 [12 13 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 12 13]
 [26 22 20]
 [17 20 10]]
[[ -8  -8 -13]
 [-10  -6  -8]
 [ -7  -6 -10]]
[[105  20   0]
 [144 112  84]
 [ 60  91   0]]
[[0.46666667 0.2        0.        ]
 [0.44444444 0.57142857 0.42857143]
 [0.41666667 0.53846154 0.        ]]


In [90]:
list1 = [1,2,3,4,5]
list2= [6,7,8,9,10]
l3 = (list1+list2)
l3

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [93]:
a= np.random.randint(1,50,(3,3))
b= np.random.randint(50,100,(3,3))

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[120 109 116]
 [127 138  74]
 [ 89  99 115]]
[[-74 -25 -52]
 [-51 -58 -44]
 [-35 -87 -45]]
[[2231 2814 2688]
 [3382 3920  885]
 [1674  558 2800]]
[[0.2371134  0.62686567 0.38095238]
 [0.42696629 0.40816327 0.25423729]
 [0.43548387 0.06451613 0.4375    ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[4 7 7]
 [3 9 9]
 [4 9 7]]
[[11 12 10]
 [19 14 16]
 [10 19 15]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19 17]
 [22 23 25]
 [14 28 22]]
[[ -7  -5  -3]
 [-16  -5  -7]
 [ -6 -10  -8]]
[[ 44  84  70]
 [ 57 126 144]
 [ 40 171 105]]
[[0.36363636 0.58333333 0.7       ]
 [0.15789474 0.64285714 0.5625    ]
 [0.4        0.47368421 0.46666667]]


In [96]:
a= np.random.randint(1,50,(3,3))
b= np.random.randint(50,100,(3,3))


array([[66, 51, 63],
       [54, 92, 74],
       [99, 72, 93]])

In [97]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[111  68  85]
 [ 85  93 122]
 [144  91 122]]
[[-21 -34 -41]
 [-23 -91 -26]
 [-54 -53 -64]]
[[2970  867 1386]
 [1674   92 3552]
 [4455 1368 2697]]
[[0.68181818 0.33333333 0.34920635]
 [0.57407407 0.01086957 0.64864865]
 [0.45454545 0.26388889 0.31182796]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 2 2]
 [8 0 7]]
(2, 3)


In [ ]:
# transpose chanin 2,3 to 3,2
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 8]
 [2 0]
 [2 7]]
(3, 2)


In [99]:
ary= np.random.randint(1,10,(2,3))
print(ary)
print(ary.shape)

[[2 2 9]
 [5 7 5]]
(2, 3)


In [100]:
transary= np.transpose(ary)
print(transary)
print(transary.shape)

[[2 5]
 [2 7]
 [9 5]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 0]
 [2 5 9]]
(2, 3)


In [ ]:
trans2 = array.T  # anotehr method of tranpose
print(trans2)
print(trans2.shape)

[[8 2]
 [1 5]
 [0 9]]
(3, 2)


In [101]:
ary= np.random.randint(1,10,(2,3))
print(ary)
print(ary.shape)

[[2 2 6]
 [7 6 7]]
(2, 3)


In [102]:
trans2 = ary.T
print(trans2)
print(trans2.shape)


[[2 7]
 [2 6]
 [6 7]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 3 7]
 [4 6 6]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 3]
 [7 4]
 [6 6]]
(3, 2)


In [104]:
ary= np.random.randint(1,10,(2,3))
print(ary)
print(ary.shape)

[[4 4 5]
 [4 2 1]]
(2, 3)


In [107]:
rary = ary.reshape(3,2)
print(rary)
print(rary.shape)

[[4 4]
 [5 4]
 [2 1]]
(3, 2)
