# Importing a libraries in Python

In [1]:
import math # math is librery.
a = 16
print(math.sqrt(a))

4.0


In [36]:
import math # math is librery.
a = 81
print(math.sqrt(81))

9.0


In [2]:
import math as m
a = 16
print(m.sqrt(a))

4.0


In [3]:
from math import sqrt,sin

print('sqrt is',sqrt(16))
print('sin val is',sin(16))

sqrt is 4.0
sin val is -0.2879033166650653


# Numpy Library

In [4]:
import numpy
print (numpy.__version__)

1.22.4


In [ ]:
# array si group of similar kind of element
# numpy use to accesse n dimentional array.

In [5]:
# Numpy Array 
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

# created simple array.

[1 2 3 4 5]


In [6]:
type(a)

numpy.ndarray

In [7]:
# 0D Array
a1 = np.array(0)
print(a1)
type(a1)

 # singel element.

0


numpy.ndarray

In [8]:
# 1D array
#import numpy as np
a2 = np.array([1,2,3,4,5])
print(a2)

[1 2 3 4 5]


In [9]:
# 2D array
import numpy as np
a3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])    #([[],[]])
print(a3)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
# 2D array
import numpy as np
a3 = np.array([[1,2,3],[1,2,3],[1,2,3]])    #([[],[]])
print(a3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
# Printing the dimesnions of array with ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


0
1
2


In [12]:
# Broadcasting Concept
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
b = 5
c = a + b   #Broadcasting  , means adding the value to the elements of array.
print('-----------')
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
# Array manipulation functions shape,reshape,concatenate
# shape function
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a
print(a.shape)

# tells about rows and column.


(2, 3)


In [14]:
# reshape function
import numpy as np
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(b)
print(b.shape)

c = b.reshape(3,4)
print(c)

c = b.reshape(4,3)
print(c)

c = b.reshape(3,2,2)
print(c)
print(c.ndim)

# converrting or reshaping the elemnt should match.

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [15]:
# Array manipulation functions 
# concatenate function
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9])
a3 = np.concatenate((a1,a2)) # simply adding element to the array
print(a3)

[1 2 3 4 5 6 7 8 9]


In [16]:
# Numpy string functions 
# add function
# adding index wise.
import numpy as np
a1 = np.array(['Hello','World'])
a2 = np.array(['Welcome','Learner'])
a3 = np.char.add(a1,a2)
print(a3)

['HelloWelcome' 'WorldLearner']


In [17]:
# Numpy string functions 
# replace function
import numpy as np
str = 'Hello How are you'
print(str)

a= np.char.replace(str, 'Hello','Hi')
print(a)

Hello How are you
Hi How are you


In [18]:
# Numpy string functions 
# upper, lower function
import numpy as np
str = 'Hello How are you'
print(str)

a= np.char.upper(str)
print(a)

b= np.char.lower(a)
print(b)

print(np.char.title(a))

Hello How are you
HELLO HOW ARE YOU
hello how are you
Hello How Are You


In [19]:
# Numpy arithmetic functions 
# add function
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])
c = np.add(a1,a2)
print(c)

[ 2  4  6  8 10]


In [20]:
# Numpy arithmetic functions 
# subtract function
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])
c = np.subtract(a1,a2)
print(c)

[0 0 0 0 0]


In [21]:
# Numpy arithmetic functions 
# mod function
import numpy as np
a1 = np.array([10,20,30,40,50])
a2 = np.array([3,2,3,4,5])
c = np.mod(a1,a2)
print(c)



# leave reminder of the array elements.

[1 0 0 0 0]


In [22]:
# Numpy arithmetic functions 
# power function
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6])
c = np.power(a1,a2)
print(c)

[    1     8    81  1024 15625]


In [23]:
# Numpy statistical functions 
# mean, median
import numpy as np
a1 = np.array([1,2,3,4,5])
print(np.median(a1))
print(np.mean(a1))

3.0
3.0


In [24]:
# Numpy Array Indexing
import numpy as np
a1 = np.array([1,2,3,4,5])
print(a1[0])
print(a1[2])
print(a1[-1])

1
3
5


In [25]:
# Numpy 2DArray Indexing
import numpy as np
a1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a1)
print(a1[0,2]) # 0 row and 3rd element
print(a1[1,3]) # 1 row and 4th element

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
9


In [26]:
# Numpy Array Slicing
import numpy as np
a1 = np.array([1,2,3,4,5,6])  
print(a1)
print(a1[1:4])
print(a1[:5])
print(a1[0:])
print(a1[1:6:2]) # we are giveing start end and fetch/ step size.
print(a1[-5:-1])

[1 2 3 4 5 6]
[2 3 4]
[1 2 3 4 5]
[1 2 3 4 5 6]
[2 4 6]
[2 3 4 5]


In [27]:
# Numpy arange function arange(start,stop,step)
import numpy as np
print(np.arange(0,10))
print(np.arange(1,10,2))

# more useful.

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [28]:
# Numpy linspace function arange(start,stop,num)
import numpy as np
print(np.linspace(1,10,20))
# it will generate decimal point number.

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


# Random Number Generation

In [29]:
# using random(): generate random float no in range 0 to 1
import random as r
import numpy as np

# print(np.random.random())
# print(np.random.random())
print(r.random())

0.40655197026902223


In [30]:
# using randn(): generate random float no in range 0 to 1, follow std normal deviation
import random
print(np.random.randn(2,3))
print(np.random.randn())

[[ 1.0266933  -0.59958934 -0.31264224]
 [-0.32078318 -0.4419097   1.59484053]]
1.4270629862264155


In [31]:
# using randint(start,end): generate random int no in range start to end
print(np.random.randint(1,5))
print(np.random.randint(1,10,5))
print(np.random.randint(1,10,(2,2)))

4
[3 5 6 4 9]
[[7 1]
 [5 5]]


In [32]:
#using seed()  to generate fix random number
# same number again and again.

import random
import numpy as np

np.random.seed(10)
print(np.random.random())

np.random.seed(5)
print(np.random.random())

np.random.seed(10)
print(np.random.random())



0.771320643266746
0.22199317108973948
0.771320643266746


In [33]:
# ravel() It returns flattend 1D array
# from Nd to 1d array.

import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(np.ravel(x))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
import numpy as np
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.zeros(5))
print(np.ones(5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
